kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: ${NAMESPACE}
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: ${APP_BASE_URL}

    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: ${APP_BASE_URL}
      cors:
        origin: ${APP_BASE_URL}

    signInPage: oidc

    auth:
      environment: production
      session:
        secret: ${BACKEND_SECRET}
      providers:
        oidc:
          production:
            metadataUrl: ${KEYCLOAK_BASE}/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            prompt: auto
            additionalScopes:
              - profile
              - email
            signIn:
              resolvers:
                - resolver: emailLocalPartMatchingUserEntityName

    catalog:
      locations:
        - type: url
          target: https://github.com/ansible/ansible-rhdh-templates/blob/main/all.yaml
          rules:
            - allow: [Template]
      rules:
        - allow: [Component, System, API, Resource, Location, User, Group, Template]
      providers:
        keycloakOrg:
          default:
            baseUrl: ${KEYCLOAK_BASE}
            loginRealm: ${KEYCLOAK_REALM}
            realm: ${KEYCLOAK_REALM}
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            schedule:
              frequency:
                minutes: 1
              timeout:
                minutes: 1
              initialDelay:
                seconds: 15
    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: user:default/admin
        policies-csv-file: /opt/app-root/src/rbac-policy.csv
    ansible:
      creatorService:
        baseUrl: 127.0.0.1
        port: '8000'
      rhaap:
        baseUrl: 'https://MyControllerUrl'
        token: '<AAP Personal Access Token>'
        checkSSL: true
