kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
  namespace: ${NAMESPACE}
stringData:
  BACKEND_SECRET: ${BACKEND_SECRET}
  KEYCLOAK_BASE: ${KEYCLOAK_BASE}
  KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
  KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
